Traceback (most recent call last):
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/huggingface_hub/utils/_http.py", line 409, in hf_raise_for_status
    response.raise_for_status()
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/requests/models.py", line 1026, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext.py

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/datasets/load.py", line 982, in dataset_module_factory
    api.hf_hub_download(
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 5514, in hf_hub_download
    return hf_hub_download(
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1008, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1071, in _hf_hub_download_to_cache_dir
    (url_to_download, etag, commit_hash, expected_size, xet_file_data, head_call_error) = _get_metadata_or_catch_error(
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1533, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1450, in get_hf_file_metadata
    r = _request_wrapper(
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 305, in _request_wrapper
    return _request_wrapper(method=method, url=next_url, follow_relative_redirects=True, **params)
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 286, in _request_wrapper
    response = _request_wrapper(
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 310, in _request_wrapper
    hf_raise_for_status(response)
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/huggingface_hub/utils/_http.py", line 420, in hf_raise_for_status
    raise _format(EntryNotFoundError, message, response) from e
huggingface_hub.errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-68dd2c0b-14317d022c10ae663c0c3fdb;4e647c45-f778-4237-b8ef-7edb952fd5ae)

Entry Not Found for url: https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext.py.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohamed/Documents/elliot_tazmani/llm_wm/train.py", line 16, in <module>
    dataloader = create_dataset(opt)
  File "/home/mohamed/Documents/elliot_tazmani/llm_wm/data/__init__.py", line 57, in create_dataset
    data_loader = CustomDatasetDataLoader(opt)
  File "/home/mohamed/Documents/elliot_tazmani/llm_wm/data/__init__.py", line 77, in __init__
    self.dataset = dataset_class(opt)
  File "/home/mohamed/Documents/elliot_tazmani/llm_wm/data/causallm_dataset.py", line 35, in __init__
    raw = load_dataset(opt.dataset_name, **ds_kwargs,
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/datasets/load.py", line 1392, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/datasets/load.py", line 1132, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/datasets/load.py", line 996, in dataset_module_factory
    return HubDatasetModuleFactory(
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/datasets/load.py", line 591, in get_module
    standalone_yaml_path = cached_path(
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/datasets/utils/file_utils.py", line 171, in cached_path
    output_path = huggingface_hub.HfApi(
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 5514, in hf_hub_download
    return hf_hub_download(
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1008, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1071, in _hf_hub_download_to_cache_dir
    (url_to_download, etag, commit_hash, expected_size, xet_file_data, head_call_error) = _get_metadata_or_catch_error(
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1533, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1450, in get_hf_file_metadata
    r = _request_wrapper(
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 286, in _request_wrapper
    response = _request_wrapper(
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 309, in _request_wrapper
    response = http_backoff(method=method, url=url, **params, retry_on_exceptions=(), retry_on_status_codes=(429,))
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/huggingface_hub/utils/_http.py", line 310, in http_backoff
    response = session.request(method=method, url=url, **kwargs)
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/huggingface_hub/utils/_http.py", line 96, in send
    return super().send(request, *args, **kwargs)
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/site-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/socket.py", line 716, in readinto
    return self._sock.recv_into(b)
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/ssl.py", line 1275, in recv_into
    return self.read(nbytes, buffer)
  File "/home/mohamed/miniconda3/envs/llm_wm/lib/python3.9/ssl.py", line 1133, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt
